name: PHPCS check

on: push

jobs:
  phpcs:
      name: PHPCS
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2

        - name: Setup PHP
          uses: shivammathur/setup-php@v2
          with:
            php-version: '7.3'
            tools: cs2pr

        - name: Run PHPCS
          run: vendor/bin/phpcs -q --report=checkstyle --ignore=*/mahalle/* | cs2pr