on: [push]
name: PHPStan

jobs:
  phpstan:
    name: phpstan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Analyse
        uses: actions-x/phpstan@v1
        with:
          arguments: --memory-limit=512M